project:
  type: book
  output-dir: docs

book:
  title: "Final Paper"
  author: "Brooke Sasia & Sarah Salas"
  date: "5/5/2023"
  chapters:
    - index.qmd
    - Intro.qmd
    - Methods.qmd
    - Results1.qmd
    - Results2.qmd
    - Discussion.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

