# Chapter 2

[@pengIntroductionLogisticRegression2002]

Provide detailed information on constructs/variables in your mini-dataset (you can choose how you present this)

## Brooke

Description of factors

The three factors have the following variables:

Factor One: 1) energy, 2) loudness 3) acousticness, 4) liveness.

Factor Two: 1) danceability, 2) valence, 3) speechiness, 4) tempo, 5) instrumentalness,

Factor Three: 1) mode, 2) key.

From this, I'm going to give the factors different names that are more descriptive than PA1-PA3. Factor One seems to describe the intensity of a song and a measurable amount of property, so I'll rename Factor One to pa1_intensity (pa = principal axis and 1 = originally factor 1). Factor Two seems to describe level of involvement, which may be a little bit of a stretch, but involvement meaning the extent to which singers, instruments, and movement (i.e., dancing) contribute to a song. I'll rename Factor Two to pa2_involvement. Finally, Factor Three is pretty basic and describe very technical aspects of songs, so I'll rename Factor Three to pa3_technicality.

## Sarah

Table 1: Caption Variable Name Variable Type Variable Description X integer Duration of song in minutes length numeric Whether the track is a song song numeric Whether the track is both live and acoustic
